import { SkillClip, VideoAnalysisSession } from '@/types/skillLibrary'

export const MOCK_CLIPS: SkillClip[] = [
  {
    id: 'clip-001',
    title: 'Right Diagonal Attack Counter',
    originalVideoName: 'silambam_training_session_01.mp4',
    timestampStart: '00:12',
    timestampEnd: '00:18',
    category: 'counter_attack',
    skillType: 'Veechu Counter',
    fighterAAction: 'Right diagonal overhead strike targeting left shoulder',
    fighterBAction: 'Late block with stick — stepped backward in straight line',
    attackDescription: 'Fighter A launches right diagonal strike from high guard. Fast wind-up, committed weight forward.',
    defenseDescription: 'Fighter B blocks late, stick slightly off-angle. Backward linear retreat — no angle change.',
    counterAttackSuggestion: 'Outside angle step (right foot pivots right 45°) → parry strike outward → immediate body counter with both hands to ribs',
    footworkExplanation: 'Instead of straight retreat, pivot to Fighter A\'s outside. This removes target and creates open counter lane.',
    mistakeDetected: 'Linear retreat without angle change. Stick block too late — wrist not firm at contact.',
    correctSolution: 'Angle-step right, absorb block, counter to body while Fighter A over-extends after follow-through.',
    coachNote: 'This is the most common defensive error in Silambam. Straight retreat gives Fighter A second chance. Always change angle on defense.',
    ruleDecision: 'No score — block was legal but no counter landed.',
    pointDecision: 'No point',
    difficulty: 'intermediate',
    tags: ['counter', 'diagonal', 'angle-step', 'defense error', 'veechu'],
    savedFolder: 'Counter Attack Techniques',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    attackDirection: 'right',
    impactZone: 'body',
    reactionTimeMs: 320,
    poseKeyframes: [
      { frameIndex: 0, timestampMs: 0, phase: 'ready', fighterA: { x: 0.3, y: 0.5, headAngle: 0, armAngle: 45, legSpread: 0.3, stickAngle: 60, stickLength: 0.35 }, fighterB: { x: 0.7, y: 0.5, headAngle: 0, armAngle: -30, legSpread: 0.3, stickAngle: 120, stickLength: 0.35 } },
      { frameIndex: 1, timestampMs: 200, phase: 'attack', fighterA: { x: 0.35, y: 0.45, headAngle: 10, armAngle: 120, legSpread: 0.4, stickAngle: 30, stickLength: 0.35, highlight: true }, fighterB: { x: 0.7, y: 0.5, headAngle: -5, armAngle: -20, legSpread: 0.3, stickAngle: 110, stickLength: 0.35 } },
      { frameIndex: 2, timestampMs: 350, phase: 'impact', fighterA: { x: 0.38, y: 0.48, headAngle: 15, armAngle: 140, legSpread: 0.45, stickAngle: 15, stickLength: 0.35, highlight: true }, fighterB: { x: 0.68, y: 0.5, headAngle: -10, armAngle: 10, legSpread: 0.35, stickAngle: 90, stickLength: 0.35, highlight: true } },
      { frameIndex: 3, timestampMs: 500, phase: 'counter', fighterA: { x: 0.36, y: 0.5, headAngle: 5, armAngle: 80, legSpread: 0.35, stickAngle: 45, stickLength: 0.35 }, fighterB: { x: 0.75, y: 0.5, headAngle: -5, armAngle: -40, legSpread: 0.3, stickAngle: 130, stickLength: 0.35 } },
    ],
  },
  {
    id: 'clip-002',
    title: 'Body Touch — Legal Score',
    originalVideoName: 'silambam_training_session_01.mp4',
    timestampStart: '00:30',
    timestampEnd: '00:34',
    category: 'combat',
    skillType: 'Two-Hand Body Strike',
    fighterAAction: 'Two-hand controlled body touch — cane tip contacts torso cleanly',
    fighterBAction: 'Defense failed — guard too high, body zone unprotected',
    attackDescription: 'Fighter A executes controlled thrust-type touch with both hands on stick. Proper legal contact — controlled, not excessive force.',
    defenseDescription: 'Fighter B\'s guard position too high (protecting head only). Lower body left open.',
    counterAttackSuggestion: 'After point reset, Fighter B should change guard height. Mix high-low guard to deny clear body targets.',
    footworkExplanation: 'Fighter A maintained distance precisely — stepped in to touching range, not past it.',
    mistakeDetected: 'Fighter B one-dimensional guard — only covers head zone. No dynamic guard movement.',
    correctSolution: 'Vary guard between head and body. When opponent threatens low, drop stick tip to cover body. Use triangular footwork to make body zone smaller.',
    coachNote: 'Legal body touch, correctly awarded 1 point. This shows proper distance management and controlled contact.',
    ruleDecision: 'Legal — controlled two-hand contact. Point awarded.',
    pointDecision: '1 point to Fighter A',
    difficulty: 'beginner',
    tags: ['legal', 'point scored', 'body touch', 'guard error', 'two-hand'],
    savedFolder: 'Combat Skills',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    attackDirection: 'thrust',
    impactZone: 'body',
    reactionTimeMs: 180,
    poseKeyframes: [
      { frameIndex: 0, timestampMs: 0, phase: 'ready', fighterA: { x: 0.3, y: 0.5, headAngle: 0, armAngle: 30, legSpread: 0.3, stickAngle: 80, stickLength: 0.35 }, fighterB: { x: 0.7, y: 0.5, headAngle: 0, armAngle: -60, legSpread: 0.3, stickAngle: 100, stickLength: 0.35 } },
      { frameIndex: 1, timestampMs: 150, phase: 'attack', fighterA: { x: 0.38, y: 0.5, headAngle: 5, armAngle: 90, legSpread: 0.35, stickAngle: 90, stickLength: 0.35, highlight: true }, fighterB: { x: 0.7, y: 0.5, headAngle: 0, armAngle: -60, legSpread: 0.3, stickAngle: 100, stickLength: 0.35 } },
      { frameIndex: 2, timestampMs: 280, phase: 'impact', fighterA: { x: 0.42, y: 0.5, headAngle: 8, armAngle: 90, legSpread: 0.38, stickAngle: 90, stickLength: 0.35, highlight: true }, fighterB: { x: 0.7, y: 0.52, headAngle: -8, armAngle: -50, legSpread: 0.3, stickAngle: 105, stickLength: 0.35, highlight: true } },
      { frameIndex: 3, timestampMs: 400, phase: 'reset', fighterA: { x: 0.3, y: 0.5, headAngle: 0, armAngle: 30, legSpread: 0.3, stickAngle: 80, stickLength: 0.35 }, fighterB: { x: 0.7, y: 0.5, headAngle: 0, armAngle: -30, legSpread: 0.3, stickAngle: 100, stickLength: 0.35 } },
    ],
  },
  {
    id: 'clip-003',
    title: 'One-Hand Touch — No Score',
    originalVideoName: 'silambam_training_session_01.mp4',
    timestampStart: '00:45',
    timestampEnd: '00:49',
    category: 'mistake_correction',
    skillType: 'Rule Violation — Single Hand',
    fighterAAction: 'Stick contact made with only one hand on cane during strike',
    fighterBAction: 'Contact received — protested as no-point',
    attackDescription: 'Fighter A attacked but right hand released grip during follow-through. Only left hand maintained contact with stick at moment of touch.',
    defenseDescription: 'Fighter B made no significant defense — received touch.',
    counterAttackSuggestion: 'No counter needed — referee stops for rule clarification. Resume from stance.',
    footworkExplanation: 'Footwork was good, but grip loss nullified the score.',
    mistakeDetected: 'Single-hand grip at moment of contact. Rule requires both hands on cane for legal score.',
    correctSolution: 'Maintain firm two-hand grip throughout entire strike sequence. Right hand must not release until after complete follow-through and recovery.',
    coachNote: 'Drill: Place tape markers on stick where both hands must stay. Practice 100 strikes per day maintaining contact. Common in beginners rushing the follow-through.',
    ruleDecision: 'No score — single hand contact is illegal per Silambam competition rules.',
    pointDecision: 'No point — rule violation',
    difficulty: 'beginner',
    tags: ['rule violation', 'single hand', 'no point', 'grip', 'correction'],
    savedFolder: 'Mistakes & Corrections',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    attackDirection: 'right',
    impactZone: 'body',
    reactionTimeMs: 0,
    poseKeyframes: [
      { frameIndex: 0, timestampMs: 0, phase: 'ready', fighterA: { x: 0.3, y: 0.5, headAngle: 0, armAngle: 45, legSpread: 0.3, stickAngle: 60, stickLength: 0.35 }, fighterB: { x: 0.7, y: 0.5, headAngle: 0, armAngle: -30, legSpread: 0.3, stickAngle: 120, stickLength: 0.35 } },
      { frameIndex: 1, timestampMs: 200, phase: 'attack', fighterA: { x: 0.36, y: 0.5, headAngle: 8, armAngle: 100, legSpread: 0.38, stickAngle: 40, stickLength: 0.35, highlight: true }, fighterB: { x: 0.68, y: 0.5, headAngle: -5, armAngle: -20, legSpread: 0.3, stickAngle: 115, stickLength: 0.35 } },
      { frameIndex: 2, timestampMs: 320, phase: 'impact', fighterA: { x: 0.4, y: 0.52, headAngle: 12, armAngle: 110, legSpread: 0.4, stickAngle: 30, stickLength: 0.35, highlight: true }, fighterB: { x: 0.68, y: 0.52, headAngle: -8, armAngle: -10, legSpread: 0.32, stickAngle: 110, stickLength: 0.35, highlight: true } },
    ],
  },
  {
    id: 'clip-004',
    title: 'Ring Exit Penalty',
    originalVideoName: 'silambam_training_session_01.mp4',
    timestampStart: '01:02',
    timestampEnd: '01:07',
    category: 'ring_control',
    skillType: 'Boundary Violation',
    fighterAAction: 'Applied pressure — straight forward attack combination',
    fighterBAction: 'Retreated in straight line — both legs crossed ring boundary',
    attackDescription: 'Fighter A applied pressure with combination attack, forcing Fighter B toward boundary.',
    defenseDescription: 'Fighter B retreated in straight line without angle change — exited ring completely.',
    counterAttackSuggestion: 'Before reaching boundary: pivot 90°, use Fighter A\'s forward momentum against them, counter from side angle.',
    footworkExplanation: 'Fighter B needed to circle inside — step left or right parallel to boundary, not backward through it. Circular footwork avoids forced exits.',
    mistakeDetected: 'Straight-line retreat with no awareness of ring position. Both feet exited = maximum penalty.',
    correctSolution: 'Always know your position in ring. When within 1-2 steps of boundary: angle-step parallel to boundary. If cornered: crouch low and pivot inside Fighter A\'s attack.',
    coachNote: 'Ring awareness drill: Practice with tape boundaries. Add penalty point each time fighter exits. Forces instinctive boundary response. 2-mark deduction per competition rules.',
    ruleDecision: 'Boundary exit — both legs outside ring.',
    pointDecision: 'Deduct 2 marks from Fighter B',
    difficulty: 'intermediate',
    tags: ['ring exit', 'penalty', 'boundary', 'footwork error', 'ring control'],
    savedFolder: 'Ring Control',
    createdAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    attackDirection: 'thrust',
    impactZone: 'body',
    reactionTimeMs: 450,
    poseKeyframes: [
      { frameIndex: 0, timestampMs: 0, phase: 'ready', fighterA: { x: 0.25, y: 0.5, headAngle: 0, armAngle: 30, legSpread: 0.3, stickAngle: 75, stickLength: 0.35 }, fighterB: { x: 0.65, y: 0.5, headAngle: 0, armAngle: -30, legSpread: 0.3, stickAngle: 105, stickLength: 0.35 } },
      { frameIndex: 1, timestampMs: 250, phase: 'attack', fighterA: { x: 0.35, y: 0.5, headAngle: 5, armAngle: 70, legSpread: 0.38, stickAngle: 60, stickLength: 0.35, highlight: true }, fighterB: { x: 0.72, y: 0.5, headAngle: -5, armAngle: -25, legSpread: 0.3, stickAngle: 110, stickLength: 0.35 } },
      { frameIndex: 2, timestampMs: 420, phase: 'defense', fighterA: { x: 0.4, y: 0.5, headAngle: 8, armAngle: 80, legSpread: 0.4, stickAngle: 55, stickLength: 0.35 }, fighterB: { x: 0.82, y: 0.5, headAngle: -10, armAngle: -20, legSpread: 0.35, stickAngle: 115, stickLength: 0.35, highlight: true } },
      { frameIndex: 3, timestampMs: 600, phase: 'reset', fighterA: { x: 0.35, y: 0.5, headAngle: 0, armAngle: 45, legSpread: 0.3, stickAngle: 70, stickLength: 0.35 }, fighterB: { x: 0.5, y: 0.5, headAngle: 0, armAngle: -30, legSpread: 0.3, stickAngle: 110, stickLength: 0.35 } },
    ],
  },
  {
    id: 'clip-005',
    title: 'Sutru Spin — Missed Counter Window',
    originalVideoName: 'silambam_demo_advanced.mp4',
    timestampStart: '00:22',
    timestampEnd: '00:28',
    category: 'attack',
    skillType: 'Sutru (360° Spin Strike)',
    fighterAAction: 'Full 360° spin strike — Sutru — targeting body zone',
    fighterBAction: 'Retreated — missed counter opportunity during spin blind spot',
    attackDescription: 'Fighter A executes full body rotation Sutru. During 180° back-turned phase, fighter is momentarily vulnerable.',
    defenseDescription: 'Fighter B saw spin coming, retreated instead of closing in during blind spot.',
    counterAttackSuggestion: 'When opponent begins Sutru: step INTO the spin during the 180° back-facing phase. Short range counter to back or side before spin completes.',
    footworkExplanation: 'Counter step must be diagonal — not straight in. Diagonal entry avoids the strike arc and reaches the back zone.',
    mistakeDetected: 'Fighter B retreated — the worst response to Sutru. Retreat gives Fighter A full spin completion and scoring position.',
    correctSolution: 'Close distance diagonally during spin wind-up. Strike the exposed back during the rotation. Reset before Fighter A faces forward again.',
    coachNote: 'Sutru counters require courage — must step in, not away. Drill with slow-motion spin practice: partner steps in at exactly 180° mark.',
    ruleDecision: 'No contact — Fighter B successfully retreated. No score.',
    pointDecision: 'No point',
    difficulty: 'advanced',
    tags: ['sutru', 'spin', 'blind spot', 'counter timing', 'advanced'],
    savedFolder: 'Attack Techniques',
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    attackDirection: 'left',
    impactZone: 'body',
    reactionTimeMs: 280,
    poseKeyframes: [
      { frameIndex: 0, timestampMs: 0, phase: 'ready', fighterA: { x: 0.35, y: 0.5, headAngle: 0, armAngle: 60, legSpread: 0.4, stickAngle: 50, stickLength: 0.4 }, fighterB: { x: 0.65, y: 0.5, headAngle: 0, armAngle: -30, legSpread: 0.3, stickAngle: 120, stickLength: 0.35 } },
      { frameIndex: 1, timestampMs: 200, phase: 'attack', fighterA: { x: 0.35, y: 0.5, headAngle: 90, armAngle: 160, legSpread: 0.45, stickAngle: 10, stickLength: 0.4, highlight: true }, fighterB: { x: 0.7, y: 0.5, headAngle: -5, armAngle: -35, legSpread: 0.32, stickAngle: 115, stickLength: 0.35 } },
      { frameIndex: 2, timestampMs: 380, phase: 'attack', fighterA: { x: 0.35, y: 0.5, headAngle: 180, armAngle: 260, legSpread: 0.45, stickAngle: -40, stickLength: 0.4, highlight: true }, fighterB: { x: 0.72, y: 0.5, headAngle: -8, armAngle: -40, legSpread: 0.3, stickAngle: 118, stickLength: 0.35 } },
      { frameIndex: 3, timestampMs: 560, phase: 'reset', fighterA: { x: 0.35, y: 0.5, headAngle: 0, armAngle: 60, legSpread: 0.4, stickAngle: 50, stickLength: 0.4 }, fighterB: { x: 0.75, y: 0.5, headAngle: 0, armAngle: -30, legSpread: 0.3, stickAngle: 120, stickLength: 0.35 } },
    ],
  },
  {
    id: 'clip-006',
    title: 'Kaaladi Triangle Evasion',
    originalVideoName: 'silambam_footwork_drills.mp4',
    timestampStart: '00:08',
    timestampEnd: '00:14',
    category: 'footwork',
    skillType: 'Kaaladi (Triangular Footwork)',
    fighterAAction: 'Straight linear attack combination × 3',
    fighterBAction: 'Kaaladi triangle evasion — stepped outside all three attacks',
    attackDescription: 'Fighter A commits to straight linear triple attack. All attacks miss due to Fighter B\'s angle changes.',
    defenseDescription: 'Fighter B uses Kaaladi triangle: right diagonal → left diagonal → center. Each step changes angle, making Fighter A miss.',
    counterAttackSuggestion: 'After 3rd evasion, Fighter A is over-committed and facing wrong direction. Counter to exposed back or side immediately.',
    footworkExplanation: 'Kaaladi triangle: Start center → Step front-right 45° → Step front-left 45° → Return center. Never step backward — always diagonal or forward.',
    mistakeDetected: 'Fighter A attacked in straight line without adjusting to Fighter B\'s movement. No angle changes in attack.',
    correctSolution: 'For Fighter A: change attack angle when opponent evades. Follow the evasion direction, do not repeat same line.',
    coachNote: 'Kaaladi is the foundation of Silambam defense. Master this before any other technique. Practice 500 repetitions daily for instinctive execution.',
    ruleDecision: 'No contact on any exchange. No score.',
    pointDecision: 'No point — clean evasion',
    difficulty: 'beginner',
    tags: ['kaaladi', 'footwork', 'evasion', 'triangle', 'foundation'],
    savedFolder: 'Footwork Skills',
    createdAt: new Date().toISOString(),
    attackDirection: 'thrust',
    impactZone: 'body',
    reactionTimeMs: 120,
    poseKeyframes: [
      { frameIndex: 0, timestampMs: 0, phase: 'ready', fighterA: { x: 0.3, y: 0.5, headAngle: 0, armAngle: 40, legSpread: 0.32, stickAngle: 65, stickLength: 0.35 }, fighterB: { x: 0.7, y: 0.5, headAngle: 0, armAngle: -30, legSpread: 0.3, stickAngle: 110, stickLength: 0.35 } },
      { frameIndex: 1, timestampMs: 180, phase: 'attack', fighterA: { x: 0.38, y: 0.5, headAngle: 5, armAngle: 80, legSpread: 0.38, stickAngle: 55, stickLength: 0.35, highlight: true }, fighterB: { x: 0.76, y: 0.45, headAngle: 5, armAngle: -20, legSpread: 0.35, stickAngle: 105, stickLength: 0.35 } },
      { frameIndex: 2, timestampMs: 340, phase: 'defense', fighterA: { x: 0.42, y: 0.5, headAngle: 5, armAngle: 85, legSpread: 0.4, stickAngle: 50, stickLength: 0.35 }, fighterB: { x: 0.72, y: 0.55, headAngle: -5, armAngle: -25, legSpread: 0.35, stickAngle: 112, stickLength: 0.35 } },
      { frameIndex: 3, timestampMs: 500, phase: 'counter', fighterA: { x: 0.44, y: 0.5, headAngle: 8, armAngle: 90, legSpread: 0.42, stickAngle: 45, stickLength: 0.35 }, fighterB: { x: 0.68, y: 0.5, headAngle: 0, armAngle: -30, legSpread: 0.3, stickAngle: 108, stickLength: 0.35 } },
    ],
  },
]

export const MOCK_SESSION: VideoAnalysisSession = {
  id: 'session-001',
  videoName: 'silambam_training_session_01.mp4',
  videoUrl: '',
  uploadedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  status: 'completed',
  totalClipsDetected: 4,
  categoriesDetected: ['counter_attack', 'combat', 'mistake_correction', 'ring_control'],
  summary: 'ORION detected 4 key exchanges. Main issues: linear retreat patterns, single-hand grip violation, ring boundary awareness. Recommended focus: Kaaladi footwork, two-hand grip drills, ring positioning awareness.',
  clips: MOCK_CLIPS.slice(0, 4),
}
